sudo: false
language: ruby
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
  - jruby-head
script:
  - bundle exec rspec spec
env:
  global:
    - JRUBY_OPTS="--server -Xcompile.invokedynamic=false --debug"
before_install:
  - "echo -e 'gem: --no-ri --no-rdoc\ninstall: --no-ri --no-rdoc\nupdate: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
install: bundle install --jobs=3 --retry=3
notifications:
  email: false
